use std::fmt::Write as _;

/// Every command registered in `generate_handler!` in `src/lib.rs`, in order.
/// The invoke handler stays the single list of commands: the permission
/// manifest and the main window's grant are derived from it here.
fn app_commands() -> Vec<String> {
    let lib = std::fs::read_to_string("src/lib.rs").expect("read src/lib.rs");
    let marker = "generate_handler![";
    let start = lib.find(marker).expect("generate_handler! in src/lib.rs") + marker.len();
    let end = start + lib[start..].find(']').expect("end of generate_handler!");
    lib[start..end]
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| entry.rsplit("::").next().unwrap_or(entry).to_string())
        .collect()
}

/// Write `contents` only when it differs, so the build script does not keep
/// invalidating itself through tauri-build's `rerun-if-changed=permissions`.
fn write_if_changed(path: &str, contents: &str) {
    if std::fs::read_to_string(path).ok().as_deref() != Some(contents) {
        std::fs::write(path, contents).unwrap_or_else(|e| panic!("write {path}: {e}"));
    }
}

fn main() {
    println!("cargo:rerun-if-changed=src/lib.rs");
    let commands = app_commands();

    // The main window may call every app command; the secondary windows get
    // the hand-picked sets in permissions/windows.toml.
    let mut main_window = String::from(
        "# Generated by build.rs from generate_handler! in src/lib.rs. Do not edit.\n\n\
         [[set]]\n\
         identifier = \"main-window\"\n\
         description = \"Every app command, for the main window.\"\n\
         permissions = [\n",
    );
    for command in &commands {
        writeln!(main_window, "  \"allow-{}\",", command.replace('_', "-")).unwrap();
    }
    main_window.push_str("]\n");
    std::fs::create_dir_all("permissions").expect("create permissions dir");
    write_if_changed("permissions/main-window.toml", &main_window);

    // Declaring the commands makes them permissioned: a window can only invoke
    // what its capability grants (allow-<command>).
    let commands: &'static [&'static str] = Box::leak(
        commands
            .into_iter()
            .map(|command| &*Box::leak(command.into_boxed_str()))
            .collect::<Vec<&'static str>>()
            .into_boxed_slice(),
    );
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(commands)),
    )
    .expect("failed to run tauri-build");
}
