<!-- Generated by scripts/make-logo.mjs -- change the mark there, not here. -->
<script lang="ts">
  let { class: className = "" }: { class?: string } = $props();
</script>

<svg viewBox="13.4 13.6 73.5 73.5" class={className} aria-hidden="true">
  <g fill="none" stroke="currentColor" stroke-width="13" stroke-linecap="round">
    <path d="M74 20L74 60" />
    <path d="M74 60C74 82 52 86 43 74" />
  </g>
  <ellipse cx="36" cy="71" rx="17" ry="11" transform="rotate(-24 36 71)" fill="currentColor" />
</svg>
